INSERT INTO `$prefixmodels_fields` (`mid`, `field_name`, `nick_name`, `tips`, `pattern`, `field_len`, `form_type`, `field_setting`, `field_status`, `input_attr`, `sort`) VALUES
($mid, 'title', '标题', '1-60个字符之间', 's1-60', 60, 'title', '{"front_field_tpl":"front.php","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_basic":"1","is_required":"1","is_unique":"2","is_posted":"1","is_disabled":"2","is_hide":"2","is_front_list":"1","is_back_list":"1","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, 'class="text title" datatype="*1-60" errormsg="标题格式不正确！"', 48),
($mid, 'cid', '导航', '', 'r/^[1-9][\\d]{0,7}$/', 8, 'navigate', '{"field_type":"mediumint","is_unsigned":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_basic":"1","is_required":"1","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, '', 50),
($mid, 'tags', '标签', '多个标签之间使用“空格”隔开', 'a|s1-60', 60, 'text', '{"field_type":"char","default_value":"","is_password":"2","front_field_tpl":"","back_field_tpl":"","front_func":"set_tags","front_func_type":"3","back_func":"set_tags","back_func_type":"3","is_basic":"1","is_required":"2","is_unique":"2","is_posted":"1","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, 'class="text tags" datatype="*1-60" ignore="ignore" errormsg="标签格式不正确！"', 46),
($mid, 'attr', '属性', '', '', 0, 'box', '{"options":"\\u63a8\\u8350|r\\r\\n\\u7279\\u8350|a\\r\\n\\u5934\\u6761|h\\r\\n\\u6eda\\u52a8|s\\r\\n\\u5e7b\\u706f|f","box_type":"checkbox","field_type":"set","is_unsigned":"1","set_value":"r,a,h,s,f","default_value":"","output_type":"2","filter_type":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_system":"1","is_basic":"1","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2"}', 1, '', 40),
($mid, 'thumbnail', '缩略图', '', '', 100, 'image', '{"field_type":"char","water_mark":"2","crop_type":"1","crop_mode":"1","crop_width":"150","crop_height":"","crop_multiple":"","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"1","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, 'class="thumbnail"', 37),
($mid, 'save_time', '发布时间', '', '', 10, 'dtime', '{"is_unsigned":"1","field_type":"int","int_format":"Y-m-d H:i:s","default_value_type":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, 'class="date"', 32),
($mid, 'a_status', '审核状态', '', '', 1, 'box', '{"options":"\\u5df2\\u5ba1\\u6838|1\\r\\n\\u672a\\u5ba1\\u6838|2\\r\\n\\u672a\\u901a\\u8fc7|3","box_type":"radio","field_type":"tinyint","is_unsigned":"1","set_value":"","default_value":"1","output_type":"2","filter_type":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_system":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2"}', 1, '', 27),
($mid, 'click', '点击数', '', 'n1-8', 8, 'numeric', '{"default_value":"120","field_type":"tinyint","is_unsigned":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_system":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2"}', 1, 'datatype="n1-8" errormsg="点击数格式不正确！" size="10"', 31),
($mid, 'good', '赞成数', '', 'n1-8', 8, 'numeric', '{"default_value":"0","field_type":"tinyint","is_unsigned":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_system":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2"}', 1, 'datatype="n1-8" errormsg="赞成数格式不正确！" size="10"', 30),
($mid, 'bad', '反对数', '', '', 8, 'numeric', '{"default_value":"0","field_type":"tinyint","is_unsigned":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_system":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2"}', 1, 'datatype="n1-8" errormsg="反对数格式不正确！" size="10"', 28),
($mid, 'sort', '排序', '', 'n1-8', 8, 'numeric', '{"default_value":"1","field_type":"tinyint","is_unsigned":"1","front_field_tpl":"","back_field_tpl":"","front_func":"","front_func_type":"1","back_func":"","back_func_type":"1","is_basic":"2","is_required":"2","is_unique":"2","is_posted":"2","is_disabled":"2","is_hide":"2","is_front_list":"2","is_back_list":"2","is_search":"2","is_fulltext":"2","is_system":"1"}', 1, 'datatype="n1-8" errormsg="排序格式不正确" class="sort" size="10"', 17);

