CREATE TABLE IF NOT EXISTS `$prefix$table` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `cid` mediumint(8) unsigned NOT NULL COMMENT '导航',
  `title` char(60) NOT NULL COMMENT '标题',
  `style` char(12) NOT NULL,
  `tags` char(60) NOT NULL COMMENT '标签',
  `description` varchar(255) NOT NULL COMMENT '摘要',
  `attr` set('r', 'a', 'h', 's', 'f') NOT NULL COMMENT '属性',
  `thumbnail` char(120) NOT NULL COMMENT '缩略图',
  `url` char(100) NOT NULL,
  `is_link` tinyint(1) unsigned NOT NULL COMMENT '转向链接',
  `save_time` int(10) unsigned NOT NULL COMMENT '发布时间',
  `click` mediumint(8) unsigned NOT NULL DEFAULT '120' COMMENT '点击数',
  `good` mediumint(8) unsigned NOT NULL COMMENT '赞成数',
  `bad` mediumint(8) unsigned NOT NULL COMMENT '反对数',
  `a_status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '审核状态',
  `is_admin` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否是管理员发布1管理员2会员 ',
  `userid` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `create_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间，此时间永不修改',
  `is_delete` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否删除至回收站1正常2删除',
  `sort` mediumint(8) unsigned NOT NULL DEFAULT '1' COMMENT '排序',
  `down_num` mediumint(8) unsigned NOT NULL COMMENT '下载次数',
  PRIMARY KEY (`id`),
  KEY `userid` (`userid`),
  KEY `orders` (`sort`,`save_time`),
  KEY `select_global` (`cid`,`userid`)
) ENGINE=MyISAM  DEFAULT CHARSET=$charset AUTO_INCREMENT=1 ;
